routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
/*Route::get('/', function () {
    return view('admin.dashboard.index');
});*/
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
Auth::routes();
Route::get('/', 'HomeController@index');
Route::resource('/user','UserController');
Route::resource('/category','CategoryController');
Route::resource('/service','ServiceController');
Route::resource('/service_fix','Service_fixController');
Route::get('/service_fix/excel/{a}','Service_fixController@excel');
Route::resource('/Fund_borrowing','Fund_borrowingController');
Route::get('/Fund_borrowing/excel/{a}','Fund_borrowingController@excel');
Route::resource('/Fund_enterpise','Fund_enterpiseController');
Route::get('/Fund_enterpise/excel/{a}','Fund_enterpiseController@excel');
Route::resource('/Fund_account','Fund_accountController');
Route::get('/Fund_account/excel/{a}','Fund_accountController@excel');
Route::get('/Fund_account/edit1/{a}','Fund_accountController@edit1');
Route::resource('/Fund_account_bill','Fund_account_billController');
Route::get('/Fund_account_bill/excel/{a}/{b}','Fund_account_billController@excel');
Route::resource('/Fund_debt','Fund_debtController');
Route::get('/Fund_debt/excel/{a}/{b}','Fund_debtController@excel');
Route::get('/Fund_debt/excel1/{a}','Fund_debtController@excel1');
Route::get('/Fund_debt/follow/{a}','Fund_debtController@follow');
Route::get('/Fund_debt/followedit/{a}','Fund_debtController@followedit');
Route::post('/Fund_debt/followedit/update_follow','Fund_debtController@update_follow');
Route::resource('/Fund_debt_all','Fund_debt_allController');
Route::get('/Fund_debt_all/excel/{a}','Fund_debt_allController@excel');
Route::resource('/Fund_debt_pass','Fund_debt_passController');
Route::resource('/Fund_debt_unpass','Fund_debt_unpassController');
Route::resource('/Fund_process','Fund_processController');
Route::resource('/Service_process','Service_processController');
Route::resource('/Fund_account_export','Fund_account_exportController');

app/Http/Controllers/Fund_borrowingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;


use App\Http\Requests\Identity_infoRequest;
use App\Http\Requests\ServiceRequest;
use App\Borrowing_info;
use App\Address;
use App\Identity_info;
use App\Identity_status;
use App\category;
use App\debt_new;
use App\debt_record_result;
use App\debt_record;
use App\Year;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;


class Fund_borrowingController extends Controller
{
  public function __construct()
  {
     $this->middleware('auth');
      $this->middleware('rent')->except('index');

  }
    public function index(){
      //$app = application_layer::all();
     // $ser = DB::table('Service')->get();
     $ser = DB::table('borrowing_info')
            ->leftJoin('Identity_status','Identity_status.borrower_id', '=', 'borrowing_info.id')
            ->leftJoin('Identity_info','Identity_info.id_rela', '=', 'Identity_status.id')
            ->leftJoin('debt_new','debt_new.id_borrower', '=', 'borrowing_info.id')
            ->leftJoin('year','year.id', '=', 'Identity_status.year')
            //->whereIn('class', ['guarantor', 'borrow'])
           // ->where('class', 'guarantor')
           ->Where('class', 'borrow')
            ->where('Identity_info.category', '1')
            ->select('*','borrowing_info.id as id_r','debt_new.name as status','Identity_info.name as namei')
            ->get();
             $ser1 = DB::table('borrowing_info')
            ->leftJoin('Identity_status','Identity_status.borrower_id', '=', 'borrowing_info.id')
            ->leftJoin('Identity_info','Identity_info.id_rela', '=', 'Identity_status.id')
            //->whereIn('class', ['guarantor', 'borrow'])
           // ->where('class', 'guarantor')
           ->Where('class', 'guarantor')
            ->where('Identity_info.category', '1')
            ->select('*','borrowing_info.id as id_r')
            ->get();

      //return view('service.index');
    // dd($ser);
      return view('fund_borrowing.index',compact('ser','ser1'));
    }
    public function create(){
        
         $ser1=array();
        $i=0;
            $ser = DB::table('Identity_status')
            ->leftJoin('Identity_info','Identity_info.id_rela', '=', 'Identity_status.id')
            ->where('Identity_info.category', '1')
            ->select('id_p')
            ->get();
            foreach($ser as $row){
                $ser1[$i] = $row->id_p;
                $i++;
            }
       $year = Year::pluck('year','id')->toArray();

    return view('fund_borrowing.create',compact('year','ser1'));
    }
    public function store(Identity_infoRequest $request)
     {
      $bowwoer = Borrowing_info::create($request->all());
         DB::table('debt_new')->insert([
             'name' => 0,
      'id_borrower' => $bowwoer->id
      ]);
        DB::table('debt_record_result')->insert([
      'id_borrower' => $bowwoer->id
      ]);
      if ($request->hasFile('pic')) {
            $fileName = $bowwoer->id . '.' .
                $request->file('pic')->getClientOriginalExtension();

            $request->file('pic')->move(
                base_path() . '/public/images/', $fileName

            );
            $busfile = DB::table('Borrowing_info')
                ->where('id', $bowwoer->id)
                ->update(['pic' => $fileName]);
        }
      $id = Identity_info::create($request->all());
      $address = Address::create($request->all());
      $status = Identity_status::create($request->all());
      $add= new Address(array(
            'address' => $request->get('address1'),
            'village' => $request->get('village1'),
            'room_number' => $request->get('room_number1'),
            'room_floor' => $request->get('room_floor1'),
            'group_home' => $request->get('group_home1'),
            'alley' => $request->get('alley1'),
            'road' => $request->get('road1'),
            'local' => $request->get('local1'),
            'district' => $request->get('district1'),
            'province' => $request->get('province1'),
            'zip_code' => $request->get('zip_code1'),
            'phone' => $request->get('phone1'),
            'category'=>'2',
        ));
        $add->save();
       $id1 = new Identity_info(array(
            'name' => $request->get('name1'),
            'surename' => $request->get('surename1'),
            'id_p' => $request->get('id_p1'),
            'id_exp' => $request->get('id_exp1'),
            'prefix' => $request->get('prefix1'),
            //'dob' => $request->get('dob1'),
            'category'=>'2',
        ));
        $id1->save();
            DB::table('Identity_info')
            ->where('id',$id1->id)
            ->update(['id_rela' => $status->id]);
            DB::table('Identity_info')
            ->where('id',$id->id)
            ->update(['id_rela' => $status->id]);
            DB::table('Address')
            ->where('id',$address->id)
            ->update(['id_rela' => $status->id]);
            DB::table('Address')
            ->where('id',$add->id)
            ->update(['id_rela' => $status->id]);
            DB::table('Identity_status')
            ->where('id',$status->id)
            ->update(['borrower_id' => $bowwoer->id]);

//-------------------------------------------------------------------------------//

      $sta = new Identity_status(array(
            'check_live' => $request->get('check_live1'),
            'live_cate' => $request->get('live_cate1'),
            'live_status' => $request->get('live_status1'),
            'c_live_status' => $request->get('c_live_status1'),
            'job' => $request->get('job1'),
            'income' => $request->get('income1'),
            'borrower_id' => $bowwoer->id,
            //'dob' => $request->get('dob1'),
            'class'=>'guarantor',
            ));
            $sta->save();

      $id2 = new Identity_info(array(
            'name' => $request->get('name2'),
            'surename' => $request->get('surename2'),
            'id_p' => $request->get('id_p2'),
            'id_exp' => $request->get('id_exp2'),
            'prefix' => $request->get('prefix2'),
            'dob' => $request->get('dob2'),
            'category'=>'1',
            'id_rela'=> $sta->id,
            ));
            $id2->save();
      $add2 = new Address(array(
            'address' => $request->get('address2'),
            'village' => $request->get('village2'),
            'room_number' => $request->get('room_number2'),
            'room_floor' => $request->get('room_floor2'),
            'group_home' => $request->get('group_home2'),
            'alley' => $request->get('alley2'),
            'road' => $request->get('road2'),
            'local' => $request->get('local2'),
            'district' => $request->get('district2'),
            'province' => $request->get('province2'),
            'zip_code' => $request->get('zip_code2'),
            'phone' => $request->get('phone2'),
            'category'=>'1',
            'id_rela'=> $sta->id,
            ));
            $add2->save();
      $add3 = new Address(array(
            'address' => $request->get('address3'),
            'village' => $request->get('village3'),
            'room_number' => $request->get('room_number3'),
            'room_floor' => $request->get('room_floor3'),
            'group_home' => $request->get('group_home3'),
            'alley' => $request->get('alley3'),
            'road' => $request->get('road3'),
            'local' => $request->get('local3'),
            'district' => $request->get('district3'),
            'province' => $request->get('province3'),
            'zip_code' => $request->get('zip_code3'),
            'phone' => $request->get('phone3'),
            'category'=>'2',
            'id_rela'=> $sta->id,
            ));
            $add3->save();
      $add4 = new Address(array(
            'address' => $request->get('address4'),
            'village' => $request->get('village4'),
            'room_number' => $request->get('room_number4'),
            'room_floor' => $request->get('room_floor4'),
            'group_home' => $request->get('group_home4'),
            'alley' => $request->get('alley4'),
            'road' => $request->get('road4'),
            'local' => $request->get('local4'),
            'district' => $request->get('district4'),
            'province' => $request->get('province4'),
            'zip_code' => $request->get('zip_code4'),
            'phone' => $request->get('phone4'),
            'category'=>'3',
            'id_rela'=> $sta->id,
            ));
            $add4->save();


    //----------------------------------------------------------------------------------//

     $sta1 = new Identity_status(array(
            'check_live' => $request->get('check_live5'),
            'live_cate' => $request->get('live_cate5'),
            'live_status' => $request->get('live_status5'),
            'c_live_status' => $request->get('c_live_status2'),
            'borrower_id' => $bowwoer->id,
            //'dob' => $request->get('dob1'),
            'class'=>'heir',
            ));
            $sta1->save();
      $id5 = new Identity_info(array(
            'name' => $request->get('name5'),
            'surename' => $request->get('surename5'),
            'id_p' => $request->get('id_p5'),
            'id_exp' => $request->get('id_exp5'),
            'prefix' => $request->get('prefix5'),
            'dob' => $request->get('dob5'),
            'category'=>'1',
            'id_rela'=> $sta1->id,
            ));
            $id5->save();
      $add5 = new Address(array(
            'address' => $request->get('address5'),
            'village' => $request->get('village5'),
            'room_number' => $request->get('room_number5'),
            'room_floor' => $request->get('room_floor5'),
            'group_home' => $request->get('group_home5'),
            'alley' => $request->get('alley5'),
            'road' => $request->get('road5'),

resources/views/fund_borrowing/index.blade.php
@extends('admin.layouts.template')
@section('page_heading')
@section('content')
        <div id="page">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"style="font-family: 'THSarabun';">งานกู้ยืมเงินผู้สูงอายุ</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
                       <!-- /.row -->

                       <div class="row">
                           <div class="col-lg-12">
                               <div class="panel panel-default">
                                   <div class="panel-heading" >
                                     <div class="col-md-3" >
                                       ข้อมูลผู้กู้ยืมเงินผู้สูงอายุ
                                     </div>
                                     <div class="col-md-6">  </div>
                                    {{ link_to_route('Fund_borrowing.create','ลงทะเบียนผู้กู้ยืมเงินกองทุน ',null,['class'=>'btn btn-success']) }}
                                   </div>
                                   <!-- /.panel-heading -->
                                   <div class="panel-body">
                                       <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                                           <thead>
                                               <tr>
                                                    <th>รหัสบัตรประชาชน</th>
                                                    <th>ชื่อผู้กู้</th>
                                                    <th>ชื่อผู้คํ้า</th>
                                                    <th>สถานะอนุมัติ</th>
                                                    <th>วันที่ยื่นกู้</th>
                                                    <th>ปีงบประมาณ</th>
                                                    <th width="170"></th>
                                               </tr>
                                           </thead>
                                           <tbody>
                                                   @foreach($ser as $user)
                                                    <tr>
                                                        <td>{{ $user->id_p}}  </td>
                                                        <td>{{ $user->namei}} {{ $user->surename}}  </td>
                                                        @foreach($ser1 as $user1)
                                                        @if($user->id_r == $user1->id_r)
                                                        <td>{{ $user1->name}} {{ $user1->surename}}  </td>
                                                        @endif
                                                         @endforeach
                                                         @if($user->status == 1)
                                                        <td>ยังไม่ทำการอนุมัติ</td>
                                                         @elseif($user->status == 2)
                                                        <td>เห็นชอบ</td>
                                                         @elseif($user->status == 3)
                                                        <td>เห็นชอบ ปรับยอดเงินกู้</td>
                                                         @elseif($user->status == 4)
                                                        <td>ไม่เห็นชอบ</td>
                                                         @else
                                                        <td>ยังไม่ทำการอนุมัติ</td>
                                                        @endif
                                                        <td>{{ $user->date}}  </td>
                                                        <td>{{ $user->year}}  </td>

                                                            <td>
                                                            {!! Form::open(array('route'=>['Fund_borrowing.destroy',$user->id_r],'method'=>'DELETE')) !!}
                                                            {{ link_to_route('Fund_borrowing.show','',[$user->id_r],['class'=>'btn btn-default glyphicon glyphicon-eye-open ']) }}
                                                            {{ link_to_route('Fund_borrowing.edit','',[$user->id_r],['class'=>'btn btn-info glyphicon glyphicon-edit ']) }}
                                                            {!! Form::button('',['class'=>'btn btn-danger glyphicon glyphicon-remove-sign del','type'=>'submit']) !!}
                                                             <a href={{ action('Fund_borrowingController@excel',[$user->id_r] )}} class="btn btn-default fa fa-print"></a>
                                                            {!! Form::close() !!}
                                                            </td>
                                                    </tr>
                                                    @endforeach
                                           </tbody>
                                       </table>
                                       <!-- /.table-responsive -->

                                   </div>
                                   <!-- /.panel-body -->
                               </div>
                               <!-- /.panel -->
                           </div>
                           <!-- /.col-lg-12 -->
                       </div>
                       <!-- /.row -->

                   </div>
                   <!-- /#page-wrapper -->

               </div>
               <!-- /#wrapper -->

@stop