routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
/*Route::get('/', function () {
    return view('admin.dashboard.index');
});*/
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
Auth::routes();
Route::get('/', 'HomeController@index');
Route::resource('/user','UserController');
Route::resource('/category','CategoryController');
Route::resource('/service','ServiceController');
Route::resource('/service_fix','Service_fixController');
Route::get('/service_fix/excel/{a}','Service_fixController@excel');
Route::resource('/Fund_borrowing','Fund_borrowingController');
Route::get('/Fund_borrowing/excel/{a}','Fund_borrowingController@excel');
Route::resource('/Fund_enterpise','Fund_enterpiseController');
Route::get('/Fund_enterpise/excel/{a}','Fund_enterpiseController@excel');
Route::resource('/Fund_account','Fund_accountController');
Route::get('/Fund_account/excel/{a}','Fund_accountController@excel');
Route::get('/Fund_account/edit1/{a}','Fund_accountController@edit1');
Route::resource('/Fund_account_bill','Fund_account_billController');
Route::get('/Fund_account_bill/excel/{a}/{b}','Fund_account_billController@excel');
Route::resource('/Fund_debt','Fund_debtController');
Route::get('/Fund_debt/excel/{a}/{b}','Fund_debtController@excel');
Route::get('/Fund_debt/excel1/{a}','Fund_debtController@excel1');
Route::get('/Fund_debt/follow/{a}','Fund_debtController@follow');
Route::get('/Fund_debt/followedit/{a}','Fund_debtController@followedit');
Route::post('/Fund_debt/followedit/update_follow','Fund_debtController@update_follow');
Route::resource('/Fund_debt_all','Fund_debt_allController');
Route::get('/Fund_debt_all/excel/{a}','Fund_debt_allController@excel');
Route::resource('/Fund_debt_pass','Fund_debt_passController');
Route::resource('/Fund_debt_unpass','Fund_debt_unpassController');
Route::resource('/Fund_process','Fund_processController');
Route::resource('/Service_process','Service_processController');
Route::resource('/Fund_account_export','Fund_account_exportController');

app/Http/Controllers/Fund_account_billController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;


use App\Http\Requests\DeRequest;
use App\Http\Requests\ServiceRequest;
use App\Service;
use App\Payment;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Response;


class Fund_account_billController extends Controller
{
  public function __construct()
  {
      $this->middleware('auth');
      $this->middleware('account')->except('index');

  }
    public function index(){

      /*$ser = DB::table('Payment')
             ->leftJoin('borrowing_info','borrowing_info.id', '=', 'Payment.id_borrower')
              ->select('*','Payment.id as id_r')
            ->get();*/
            $ser = DB::table('Payment')
            ->leftJoin('borrowing_info','borrowing_info.id', '=', 'Payment.id_borrower')
            ->leftJoin('identity_status','identity_status.borrower_id', '=', 'borrowing_info.id')
            ->leftJoin('identity_info','identity_info.id_rela', '=', 'identity_status.id')
            ->leftJoin('debt_record_result','debt_record_result.id_borrower', '=', 'borrowing_info.id')
            ->leftJoin('year','year.id', '=', 'Identity_status.year')
            ->select('*','Payment.id as id_r')
            ->where('class','borrow')
            ->where('Identity_info.category', '1')
            ->get();

      return view('Fund_account_bill.index',compact('ser'));
    }
    public function create(){
/*$phpWord  = new \PhpOffice\PhpWord\PhpWord();
	$section = $phpWord->createSection();
	$section->addText('Test PhpWord');
    $writer = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
    $writer->save('testword.docx');*/
	

    //return view('Fund_account_bill.create');
    }
    public function store(ServiceRequest $request)
     {
       Service::create($request->all());
       //return redirect()->route('de.index')->with('message','item has been added successfully');

    /* $u = department::create([
           'name' => $request['name'],
           'remark' => $request['remark'],

       ]);*/

        return redirect()->route('Fund_account_bill.index')->with('message','item has been added successfully');
     }

     public function show($id)
     {
        // dd($id);
        DB::table('Payment')
            ->where('id', $id)
            ->delete();

        return redirect()->route('Fund_account_bill.index');
     }

     public function edit($service)
    {

       $service = DB::table('Payment')
            ->leftJoin('borrowing_info','borrowing_info.id', '=', 'Payment.id_borrower')
            ->leftJoin('identity_status','identity_status.borrower_id', '=', 'borrowing_info.id')
            ->leftJoin('identity_info','identity_info.id_rela', '=', 'identity_status.id')
            ->leftJoin('debt_record_result','debt_record_result.id_borrower', '=', 'borrowing_info.id')
            ->where('Payment.id',$service)
            ->select('*','Payment.id as id_p')
            ->where('class','borrow')
            ->first();
    $ser = DB::table('borrowing_info')
             ->leftJoin('debt_new','debt_new.id_borrower', '=', 'borrowing_info.id')
            ->leftJoin('debt_record_result','debt_record_result.id_borrower', '=', 'borrowing_info.id')
             ->leftJoin('payment','payment.id_borrower', '=', 'borrowing_info.id')
            ->where('borrowing_info.id',$service->id_borrower)
            ->first();
            //dd($service);
        return view('Fund_account_bill.edit',compact('service','ser'));
    }

    public function update(ServiceRequest $request,$service)
   {
    //  $affectedRows = de::where('id',$de->id)->update(['name' => $de->name,'email' => $de->email,'role' => $de->role ]);
    $pay = DB::table('Payment')
         ->where('id',$service)
          ->first();
       $debt = DB::table('debt_record_result')
         ->where('id_borrower',$pay->id_borrower)
          ->first();
          $rollback = $pay->total + $debt->money_remain;
          $rollback1 =  $debt->money_payed - $pay->total;
      //  $money_remain  = $debt->money_remain - $pay->total;

    $pay1 =  DB::table('Payment')
         ->where('id',$service)
         ->update([
           'date_pay' => $request->get('date_pay'),
           'place_pay' => $request->get('place_pay'),
           'total' => $request->get('total'),
           'bill_book' => $request->get('bill_book'),
           'bill_no' => $request->get('bill_no'),
           'remark' => $request->get('remark'),
           'order_no' => $request->get('order_no'),
            'order_date' => $request->get('order_date')
         ]);
         //dd($service);
              DB::table('debt_record_result')
         ->where('id_borrower',$pay->id_borrower)
         ->update([
         'money_remain' => $rollback - $request->get('total'),
         'money_payed' => $rollback1 + $request->get('total'),
       ]);
       return redirect()->route('Fund_account_bill.index')->with('message','item has been updated successfully');
   }

     public function destroy($service)
     {
         dd($service);
        DB::table('Payment')
            ->where('id', $service)
            ->delete();

        return redirect()->route('Fund_account_bill.index');
     }
      public function excel($service , $a)
     {

            $ser2 = DB::table('Payment')
            ->leftJoin('borrowing_info','borrowing_info.id', '=', 'Payment.id_borrower')
            ->leftJoin('identity_status','identity_status.borrower_id', '=', 'borrowing_info.id')
            ->leftJoin('identity_info','identity_info.id_rela', '=', 'identity_status.id')
            ->leftJoin('debt_record_result','debt_record_result.id_borrower', '=', 'Payment.id_borrower')
            ->select('*','Payment.id as id_r','borrowing_info.money as money')
            ->where('class','borrow')
            ->where('Payment.id',$service)
            ->where('Identity_info.category', '1')
            ->first();
            //dd($ser2);
            if($a==0){
        return view('Fund_account_bill.excel',compact('ser2'));
           

            }
            if($a==1){
                 $templateProcessor = new \PhpOffice\PhpWord\TemplateProcessor(asset('/tem/bill.docx'));
    $templateProcessor->setValue('prefix', $ser2->prefix);
    $templateProcessor->setValue('name', $ser2->name);
    $templateProcessor->setValue('sname', $ser2->surename);
    $templateProcessor->setValue('no', $ser2->order_no);
    $templateProcessor->setValue('money', $ser2->total);

    $templateProcessor->saveAs('หนังสือส่งใบเสร็จ'.$ser2->name.'.docx');

    return response()->download('หนังสือส่งใบเสร็จ'.$ser2->name.'.docx'); 
       // return view('Fund_account_bill.excel1',compact('ser2'));
            }
            if($a==2){
                 $templateProcessor1 = new \PhpOffice\PhpWord\TemplateProcessor(asset('/tem/confirm.docx'));
    $templateProcessor1->setValue('prefix', $ser2->prefix);
    $templateProcessor1->setValue('name', $ser2->name);
    $templateProcessor1->setValue('sname', $ser2->surename);
    $templateProcessor1->setValue('no', $ser2->contect_id);
    $templateProcessor1->setValue('money', $ser2->money);
    $templateProcessor1->setValue('remain', $ser2->money_remain);
    $templateProcessor1->saveAs('หนังสือแจ้งยืนยันยอด'.$ser2->name.'.docx');

    return response()->download('หนังสือแจ้งยืนยันยอด'.$ser2->name.'.docx'); 
       // return view('Fund_account_bill.excel2',compact('ser2'));
            }

     }

}

resources/views/Fund_account_bill/edit.blade.php
@extends('admin.layouts.template')
@section('page_heading','Crate')
@section('content')
    <div id="page">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">แก้ไขใบเสร็จรับเงิน</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
                       <!-- /.row -->
                       {{ link_to_route('Fund_account_bill.index','ย้อนกลับ',null,['class'=>'btn btn-default pull-right']) }}
                       <br />
                       <br />

                       <div class="row">
                           <div class="col-lg-12">
                               <div class="panel panel-default">
                                   <div class="panel-heading">
                                      
                                   </div>
                                   <!-- /.panel-heading -->

                                       <div class="panel-body">
                        {!! Form::model($service,array('route'=>['Fund_account_bill.update',$service->id_p],
                        'method'=>'PUT','novalidate' => 'novalidate','files' => true)) !!}


                                <h4>ชำระเงิน</h4>
                                <hr />

                                <label class="col-lg-2 ">ชื่อ</label>
                                <input type="text" class="col-lg-3" name="" value="{{$service->name}} {{$service->surename}}" disabled=""/>
                                <label  class="col-lg-2 text-right">เลขที่สัญญา</label>
                                <div class="col-lg-5">
                                <input type="text" class="col-lg-8" name="" value="{{$service->contect_id}}" disabled=""/>
                                </div>
                                <div class="col-lg-12"> <br />  </div>

                                <label class="col-lg-2 ">วันที่ชำระ</label>
                                <input type="date" class="col-lg-3" name="date_pay" value="{{$service->date_pay}}"/>
                                <label  class="col-lg-2 text-right">ช่องทางการชำระ</label>
                                <div class="col-lg-4">
                     <input list="a" name="place_pay"  id="b"class="col-lg-10" value="{{$service->place_pay}}" >

                                        <datalist id="a">
                                        <option value="เค้าเตอร์เซอร์วิส">
                                        <option value="ธนาณัติ">
                                        <option value="จ่ายเงินสด">
                                        </datalist>

                                           
                                </div>
                                <div class="col-lg-12"> <br />  </div>


                                <label class="col-lg-2 ">ยอดชำระ</label>
                                <input type="text" class="col-lg-3" name="total" value="{{$service->total}}"  />
                                <label  class="col-lg-2 text-right" >ยอดคงเหลือ</label>
                                <div class="col-lg-5">
                                <input type="text" class="col-lg-8" disabled="" name="" value="{{$ser->money_remain}}"/>
                                </div>
                                <div class="col-lg-12"> <br />  </div>

                                <label class="col-lg-2 ">เล่มที่ใบเสร็จ</label>
                                <input type="text" class="col-lg-3"   name="bill_book" value="{{$service->bill_book}}"/>
                                <label  class="col-lg-2 text-right">เลขที่ใบเสร็จ</label>
                                <div class="col-lg-5">
                                <input type="text" class="col-lg-8" name="bill_no" value="{{$service->bill_no}}" id="a3"/>
                                </div>
                                <div class="col-lg-12"> <br />  </div>

                                <label  class="col-lg-2">หมายเหตุ</label>
                                <textarea class="col-lg-3" name="remark" >{{$service->remark}}</textarea>
                                <label  class="col-lg-7"></label>
                                <div class="col-lg-12"> <br />  </div>

                                  <div id="change">
                                <div class="col-lg-12">
                                  <h4>กรณีธนาณัติ</h4>
                                  <hr />
                                </div>

                                <label class="col-lg-2 ">เลขที่ธนาณัติ</label>
                                <input type="text" class="col-lg-3"  name="order_no" value="{{$service->order_no}}" id="a2"/>
                                <label  class="col-lg-2 text-right">วันที่ส่งธนานัติ</label>
                                <div class="col-lg-5">
                                <input type="date" class="col-lg-8" name="order_date" value="{{$service->order_date}}"id="a1"/>
                                </div>

                                </div>
                                <div class="col-lg-12"> <br />  </div>

                                 {!! Form::hidden('class', null,['id' => 'class']) !!}
                                      <div class="form-group col-lg-12" >
                                        <button type="button" id="reset" class="btn btn-danger" >ค่าเริ่มต้น</button>
                                        {!! Form::button('บันทึก',['type'=>'submit','class'=>'btn btn-primary','id'=>'add1']) !!}
                                      <a href={{ action('Fund_account_billController@excel',[$service->id_p , '1' ] )}} class="btn btn-info fa fa-print pull-right">หนังสือส่งใบเสร็จ</a>
                                      <a href={{ action('Fund_account_billController@excel',[$service->id_p , '2' ] )}} class="btn btn-primary fa fa-print pull-right">หนังสือแจ้งยอดยืนยัน</a>
                                      <a href={{ action('Fund_account_billController@excel',[$service->id_p , '0'] )}} class="btn btn-default fa fa-print pull-right">ข้อมูลใบเสร็จรับเงินรายบุลคล</a>

                                      </div>


                                    {!! Form::close() !!}
                            </form>




                                   </div>

                                   <!-- /.panel-body -->
                                    @if($errors->any())
                                    <ul class="alert alert-danger">
                                    @foreach($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                    @endforeach
                                    </ul>
                                    @endif
                               </div>
                               <!-- /.panel -->
                           </div>
                           <!-- /.col-lg-12 -->
                       </div>
                       <!-- /.row -->

                   </div>
                   <!-- /#page-wrapper -->

<script src="{{asset('/assets/bower_components/jquery/dist/jquery.min.js')}}"></script>
<script>
    $(document).ready(function() {
        var val = <?php echo json_encode($service->place_pay); ?>;
         
        if(val =='ธนาณัติ'){
            // alert(val);
               $('#change').show();
          }else{
              $('#change').hide();
          }

        $('#b').on('change',function(){
              if($('#b').val() =='ธนาณัติ'){
               $('#change').show();
          }else{
               $('#change').hide();
               $('#a2').val('');
               $('#a1').val('') ;
               //$('#a3').val('') ;
          }
          });
    });

</script>
@stop

resources/views/Fund_account_bill/excel.blade.php
 
       <?php
//คำสั่ง connect db เขียนเพิ่มเองนะ

header("Content-type: application/vnd.ms-word");
header("Content-Disposition:attachment;Filename=ใบเสร็จรับเงิน.doc  ");//
header("Pragma:no-cache");

?>
<html xmlns:o="urn:schemas-microsoft-com:office:office"xmlns:x="urn:schemas-microsoft-com:office:excel"xmlns="http://www.w3.org/TR/REC-html40">
 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<body>
<br>
<br><div width="185" align="center"  ><strong><u>ข้อมูลใบเสร็จชำระเงินงวด</u></strong></div><br>

                               <strong> ชื่อ : {{ $ser2->name}} {{ $ser2->surename}} <strong>เลขที่สัญญา : {{ $ser2->contect_id}} <br>
                             <strong> วันที่ชำระ :</strong> {{ $ser2->date_pay}} 
                               <strong>ช่องการการชำระ :</strong>{{ $ser2->place_pay}} <br>                     
                               <strong> ยอดชำระ :</strong>     {{ $ser2->total}}  
                              <strong>  ยอดคงเหลือ :</strong>{{ $ser2->money_remain}}<br>
                              <strong>  เล่มที่ใบเสร็จ :</strong> {{ $ser2->bill_book}} 
                              <strong>  เลขที่ใบเสร็จ :</strong> {{ $ser2->bill_no}}  <br>
                               <strong>  หมายเหตุ :</strong>{{ $ser2->remark}}  <br>
                                <strong>  เลขที่ธนาณัติ :</strong> {{ $ser2->order_no}}  
                                <strong>  วันที่ส่งธนาณัติ :</strong> {{ $ser2->order_no}}  
                                                        
                                                        
                                                        
                                                       
                                                       
                                                       


<script>
window.onbeforeunload = function(){return false;};
setTimeout(function(){window.close();}, 10000);
</script>
</body>
</html>



 

resources/views/Fund_account_bill/excel1.blade.php
 
       <?php
//คำสั่ง connect db เขียนเพิ่มเองนะ

header("Content-type: application/vnd.ms-word");
header("Content-Disposition:attachment;Filename=หนังสือส่งใบเสร็จ( $ser2->name  $ser2->surename ).doc  ");//
header("Pragma:no-cache");

?>
<html xmlns:o="urn:schemas-microsoft-com:office:office"xmlns:x="urn:schemas-microsoft-com:office:excel"xmlns="http://www.w3.org/TR/REC-html40">
 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<body>
<div width="185" align="center"  ><strong><img src="{{ URL::to('/') }}/images/g.jpg"  width="90" height="90"  /></strong></div>
<div width="185" align="left"  ><strong><pre>           ที่.............</pre></strong></div><div width="185" align="right"  ><strong>
<pre>
สำนักงานพัฒนาสังคมและความมั่นคงของมนุษย์จัง           
หวัดอุบลราชธานี ศาลากลางจังหวัดอุบลราชธานี            
ถนนแจ้งสนิท อบ 34000            </pre>
</strong></div>
<div width="185" align="center"  ><strong><pre>                 วันที่................</pre> </strong></div>
<div width="185" align="left"  ><strong><pre>เรื่อง  ส่งใบเสร็จรับเงินกองทุนผู้สูงอายุ </pre> </strong></div>
<div width="185" align="left"  ><strong><pre>เรียน {{ $ser2->name}} {{ $ser2->surename}}</pre></strong></div>
<div width="185" align="left"  ><strong><pre>สิ่งที่ส่งมาด้วย ใบเสร็จรับเงินกองทุนผู้สูงอายุ จำนวน 1 ฉบับ</pre> </strong></div>
<div width="185" align="left"  ><strong>
<pre>                       ตามที่ท่านได้ส่งไปรษณีย์ธนาณัติ เลขที่ธนาณัติ {{ $ser2->order_no}} ลงวันที่.....................
จำนวนเงิน {{ $ser2->total}}.00.-บาท (..............)
นำส่งสำนักงานพัฒนาสังคมและความมั่นคงของมนุษย์จังหวัดอุบลราชธานี (งานกองทุนผู้สูงอายุ)
เพื่อชำระค่างวดเงินกู้ยืมทุนประกอบอาชีพกองทุนผู้สูงอายุ นั้น
                            สำนักงานพัฒนาสังคมและความมั่นคงของมนุษย์จังหวัดอุบลราชธานี
ได้รับธนาณัติฉบับดังกล่าวข้างต้นและได้ออกใบเสร็จรับเงินเรียบร้อยแล้ว
จึงขอส่งใบเสร็จรับเงินมาเพื่อให้ท่านเก็บไว้เป็นหลักฐานต่อไป
                                        จึงเรียนมาเพื่อทราบ
                                                              ขอแสดงความนับถือ



                                                       พัฒนาสังคมและความมั่นคงของมนุษย์
                                                              จังหวัดอุบลราชธานี
       </pre> </strong></div>
<div width="185" align="left"  ><strong>
<pre>
สำนักงานพัฒนาสังคมและความมั่นคงของมนุษย์จังหวัด
ฝ่ายบริหารงานทั่วไป
โทร./โทรสาร 0-4534-4579, 0-4534-4641
</pre> </strong></div>




                                                       
                                                       


<script>
window.onbeforeunload = function(){return false;};
setTimeout(function(){window.close();}, 10000);
</script>
</body>
</html>



 


 

resources/views/Fund_account_bill/excel_test.blade.php
 @extends('admin.layouts.Sample_Header')

       <?php
$templateProcessor = new \PhpOffice\PhpWord\TemplateProcessor('public/tem/test.docx');


 


 

resources/views/Fund_account_bill/index.blade.php
@extends('admin.layouts.template')
@section('page_heading')
@section('content')
        <div id="page">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">รายการใบเสร็จรับเงิน</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
                       <!-- /.row --><br><br>

                       <div class="row">
                           <div class="col-lg-12">
                               <div class="panel panel-default">
                                   <div class="panel-heading">
                                     <div class="col-md-2-sm-3">
                                       รายการใบเสร็จรับเงิน
                                     </div>
                                   </div>

                                   <!-- /.panel-heading -->
                                   <div class="panel-body">
                                       <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                                           <thead>
                                               <tr>
                                                             <th>เล่มที่ใบเสร็จ</th>
                                                            <th>เลขที่ใบเสร็จ</th>
                                                            <th>วันที่ชำระ</th>
                                                            <th>ได้รับเงินจาก</th>
                                                            <th>เลขที่ธนาณัติ</th>
                                                            <th>เลขที่สัญญา</th>
                                                            <th>ปีงบประมาณ</th>
                                                            <th width="80"></th>
                                               </tr>
                                           </thead>
                                           <tbody>
                                                   @foreach($ser as $user)
                                                    <tr>
                                                        <td>{{ $user->bill_book}}  </td>
                                                       <td>{{ $user->bill_no}}  </td>
                                                        <td>{{ $user->date_pay}} </td>
                                                        <td>{{ $user->name}} {{ $user->surename}}</td>
                                                        <td>{{ $user->order_no}}  </td>
                                                        <td>{{ $user->contect_id}}  </td>
                                                        <td>{{ $user->year}}  </td>
                                                        <td>

                              {{ link_to_route('Fund_account_bill.edit','',[$user->id_r],['class'=>'btn btn-info glyphicon glyphicon-edit ']) }}
                            {{ link_to_route('Fund_account_bill.show','',[$user->id_r],['class'=>'btn btn-danger glyphicon glyphicon-remove-sign del ']) }}

                                                        </td>

                                                    </tr>
                                                    @endforeach

                                           </tbody>
                                       </table>
                                       <!-- /.table-responsive -->

                                   </div>
                                   <!-- /.panel-body -->
                               </div>
                               <!-- /.panel -->
                           </div>
                           <!-- /.col-lg-12 -->
                       </div>
                       <!-- /.row -->

                   </div>
                   <!-- /#page-wrapper -->

               </div>
               <!-- /#wrapper -->

@stop